### ISSUE TITLE
Why there is MonadTransNoPureAborts (ExceptT e) instance?

### ISSUE THREAD

**Issue by phadej** [obsidiansystems/rhyolite#118]
```haskell
instance (Error e, MonadBaseNoPureAborts n m, MonadTransNoPureAborts (ErrorT e)) => MonadBaseNoPureAborts n (ErrorT e m)
instance (MonadBaseNoPureAborts n m, MonadTransNoPureAborts (ExceptT e)) => MonadBaseNoPureAborts n (ExceptT e m)
instance (MonadBaseNoPureAborts n m, MonadTransNoPureAborts ListT) => MonadBaseNoPureAborts n (ListT m)
```

```haskell
noPureAbortsT :: Proxy (ExceptT t) -> Either e a -> a
```

is left undefined, an there're no comment why that invalid instance is there?

**Comment by xplat** [comment]
There is a comment: "better error messages" or something of the sort.  These instances are of `MonadBaseNoPureAborts` and serve to turn error messages that complain about being unable to satisfy `MonadBaseNoPureAborts` for an entire monad stack to ones that specifically target the `ExceptT`, `ErrorT` or `ListT` component.

**Comment by phadej** [comment]
Couldn’t a TypeError be used?

**Comment by xplat** [comment]
It seems unnecessary to change the wording here.  I wouldn't want it to be *too* different from the case where there's no instance of the main class anyway ...

**Comment by 3noch** [comment]
Actually there are no instances for `MonadTransNoPureAborts`, only `MonadBaseNoPureAborts`. If you want to implement a better mechanism for signaling where the error is, please submit a PR! However, we aren't interested in doing that ourselves at this time.
