### ISSUE TITLE
Deprecate Rhyolite.Backend.Snap.Util.FileServe.Stream ?

### ISSUE THREAD

**Issue by srid** [obsidiansystems/rhyolite#127]
This,
https://github.com/obsidiansystems/rhyolite/blob/develop/backend-snap/Rhyolite/Backend/Snap/Util/FileServe/Stream.hs

is the same as this,
https://github.com/obsidiansystems/snap-stream/blob/master/src/Snap/Util/FileServe/Stream.hs

**Comment by Ericson2314** [comment]
None of Rhyolite is stable so you can make a PR to just do that.

**Comment by 3noch** [comment]
Even better just re-export. :)

**Comment by ali-abrar** [comment]
De-duplicated.
