### ISSUE TITLE
There should be some function which runs a RhyoliteWidget, and makes use of an Obelisk route for the listen route..

### ISSUE THREAD

**Issue by cgibbard** [obsidiansystems/rhyolite#33]

**Comment by ali-abrar** [comment]
With https://github.com/obsidiansystems/rhyolite/pull/36 now you can use `Network.URI.parseURI` on the route config retrieved via `Obelisk.ExecutableConfig.get`.  `websocketUri` can be used to convert to websocket schema, and the result can be `mappend`ed to the result of `renderBackendRoute`.

The function would have to take a checked route encoder, the route config, and the actual target route to even potentially be useful, but I'm not sure how useful it'd be.

**Comment by ali-abrar** [comment]
@cgibbard what's the status of this post-refactor?

**Comment by cgibbard** [comment]
I did this one, forgot about this ticket.

**Comment by cgibbard** [comment]
https://github.com/obsidiansystems/rhyolite/blob/develop/frontend/Rhyolite/Frontend/App.hs#L285
