### ISSUE TITLE
No longer builds on Mac

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/rhyolite#6]
My money is on https://github.com/obsidiansystems/rhyolite/commit/b7329ad538b1ab7a2dd0d0ad8d1a90854992ccbd#diff-ce476d526af526449a2814274ad10fcdR36

**Comment by 3noch** [comment]
Ideas for journald stuff:

  1. Drop it
  2. Guard it with CPP + cabal flag
  3. Put it in separate library

**Comment by ryantrinkle** [comment]
That all sounds reasonable, but is there any reason we care about mac
support?
