### ISSUE TITLE
Rhyolite widgets can't prerender Semantic widgets

### ISSUE THREAD

**Issue by JBetz** [obsidiansystems/rhyolite#90]
Since IO was removed from server-side rendering, `semantic-reflex` widgets can no longer be prerendered with a `rhyolite` frontend. I'm opening this here rather than in `semantic-reflex` since it seems like IO for SSR is something we want a better way to support, so it would be good to discuss what the issues with it are, and how to address them without disallowing it entirely.

Rhyolite's removal of IO: https://github.com/obsidiansystems/rhyolite/commit/acbb903c0455a7cb6d4afb2e0e8d13c4abff73e2#diff-50255213af6249e5191f390bdce883d3

Semantic's dependence on IO: https://github.com/tomsmalley/semantic-reflex/blob/master/semantic-reflex/src/Reflex/Dom/SemanticUI/Transition.hs#L474-L476

**Comment by 3noch** [comment]
Would adding MonadIO back actually fix this? I wouldn't trust the server to build the DOM I wanted for SemUI with MonadIO in use

**Comment by ryantrinkle** [comment]
I agree with @3noch.  Any IO that's happening server-side is wrong almost by definition.

**Comment by tomsmalley** [comment]
IO should really be banned at the reflex-dom level, but iirc we haven't quite got there yet. We shouldn't be doing IO during prerendering: it's a semantic-reflex issue.

**Comment by JBetz** [comment]
Relocated to `semantic-reflex`.
